server:
  port: 8082
spring:
  application:
    name: hospital-finance
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}/postgres?currentSchema=${SCHEMA}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      config-file: classpath:kafka/consumer.xml
logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    solvd.laba.ermakovich.hf: ${APP_LOG_LEVEL}