server:
  port: 8082
spring:
  application:
    name: hospital-finance
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}/postgres?currentSchema=${SCHEMA}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/liquibaseConfig.yml
    liquibase-schema: ${SCHEMA}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}