server:
  port: ${SERVER_PORT}
spring:
  application:
    name: hospital-finance
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      config-file: src/main/resources/kafka/consumer.xml
logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    solvd.laba.ermakovich.hf: ${APP_LOG_LEVEL}
hospital-users:
  name: ${HOSPITAL_USERS_HOST}