server:
  port: 8082
spring:
  application:
    name: hospital-finance
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}/postgres?currentSchema=${SCHEMA}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/liquibaseConfig.yml
    liquibase-schema: ${SCHEMA}
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      config-file: classpath:kafka/consumer.xml
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework: ${SPRING_LOG_LEVEL}
    solvd.laba.ermakovich.hf: ${APP_LOG_LEVEL}